# Generated by Django 6.0.5 on 2026-05-09 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseExemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('s12', 's.12 — Cost of compliance limit'), ('s14', 's.14 — Vexatious or repeated request'), ('s21', 's.21 — Information accessible by other means'), ('s22', 's.22 — Intended for future publication'), ('s23', 's.23 — Information supplied by security bodies'), ('s24', 's.24 — National security'), ('s26', 's.26 — Defence'), ('s27', 's.27 — International relations'), ('s28', 's.28 — Relations within the UK'), ('s29', 's.29 — The economy'), ('s30', 's.30 — Investigations and proceedings'), ('s31', 's.31 — Law enforcement'), ('s32', 's.32 — Court records'), ('s33', 's.33 — Audit functions'), ('s34', 's.34 — Parliamentary privilege'), ('s35', 's.35 — Formulation of government policy'), ('s36', 's.36 — Prejudice to effective conduct of public affairs'), ('s37', 's.37 — Communications with the Crown'), ('s38', 's.38 — Health and safety'), ('s39', 's.39 — Environmental information'), ('s40', 's.40 — Personal information'), ('s41', 's.41 — Information provided in confidence'), ('s42', 's.42 — Legal professional privilege'), ('s43', 's.43 — Commercial interests'), ('s44', 's.44 — Prohibitions on disclosure')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exemptions', to='cases.case')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('case', 'code')},
            },
        ),
    ]
