# Generated by Django 6.0.5 on 2026-05-12 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0007_bankholiday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='assignee',
        ),
        migrations.RemoveField(
            model_name='case',
            name='department',
        ),
    ]
