# Generated by Django 6.0.5 on 2026-05-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0010_case_assignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('requester', 'Requester')], max_length=20),
        ),
    ]
