# Generated by Django 6.0.5 on 2026-06-02 14:26

from django.db import migrations, models


def migrate_statuses_forward(apps, schema_editor):
    CaseConsultation = apps.get_model("cases", "CaseConsultation")
    CaseConsultation.objects.filter(
        status__in=["pending", "awaiting_clarification"]
    ).update(status="open")
    CaseConsultation.objects.filter(status="responded").update(status="closed")


def migrate_statuses_backward(apps, schema_editor):
    CaseConsultation = apps.get_model("cases", "CaseConsultation")
    CaseConsultation.objects.filter(status="open").update(status="pending")
    CaseConsultation.objects.filter(status="closed").update(status="responded")


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0011_alter_emailtemplate_type"),
    ]

    operations = [
        migrations.RunPython(migrate_statuses_forward, migrate_statuses_backward),
        migrations.AlterField(
            model_name="caseconsultation",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="open",
                max_length=30,
            ),
        ),
    ]
