# Generated by Django 6.0.5 on 2026-06-06 14:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0012_alter_case_status"),
        ("cases", "0013_alter_caseresponse_status"),
    ]

    operations = []
