# Generated by Django 6.0.5 on 2026-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0014_merge_20260606_1516"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="type",
            field=models.CharField(
                choices=[
                    ("assignee", "Assignee"),
                    ("consultation", "Consultation"),
                    ("requester", "Requester"),
                ],
                max_length=20,
            ),
        ),
    ]
