# Generated by Django 6.0.5 on 2026-06-08 21:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cases", "0015_alter_emailtemplate_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="purpose",
            field=models.CharField(
                blank=True,
                choices=[
                    ("acknowledgement", "Acknowledgement"),
                    ("case_response", "Case Response"),
                    ("consultation_notification", "Consultation Notification"),
                    ("consultation_message", "Consultation Message"),
                    ("case_assignment", "Case Assignment"),
                ],
                max_length=40,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="emailtemplate",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("assignee", "Assignee"),
                    ("consultation", "Consultation"),
                    ("requester", "Requester"),
                ],
                max_length=20,
            ),
        ),
    ]
