# Generated by Django 6.0.5 on 2026-06-11 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0016_emailtemplate_purpose_alter_emailtemplate_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('acknowledged', 'Acknowledged'), ('with_department', 'With Department'), ('drafting', 'Drafting'), ('review', 'In Review'), ('with_applicant', 'Awaiting Clarification'), ('internal_review', 'Internal Review'), ('referred', 'Referred'), ('exempt', 'Refused / Exempt'), ('closed', 'Closed')], default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='purpose',
            field=models.CharField(blank=True, choices=[('acknowledgement', 'Acknowledgement'), ('case_response', 'Case Response'), ('consultation_notification', 'Consultation Notification'), ('consultation_message', 'Consultation Message'), ('case_assignment', 'Case Assignment'), ('clarification_request', 'Clarification Request')], max_length=40, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='CaseClarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clarification', to='cases.case')),
            ],
        ),
    ]
