# Generated by Django 6.0.5 on 2026-08-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0017_responsetemplate_alter_case_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsetemplate',
            options={'ordering': ['exemption_code', 'name']},
        ),
        migrations.AddField(
            model_name='responsetemplate',
            name='exemption_code',
            field=models.CharField(blank=True, choices=[('s12', 's.12 — Cost of compliance limit'), ('s14', 's.14 — Vexatious or repeated request'), ('s21', 's.21 — Information accessible by other means'), ('s22', 's.22 — Intended for future publication'), ('s23', 's.23 — Information supplied by security bodies'), ('s24', 's.24 — National security'), ('s26', 's.26 — Defence'), ('s27', 's.27 — International relations'), ('s28', 's.28 — Relations within the UK'), ('s29', 's.29 — The economy'), ('s30', 's.30 — Investigations and proceedings'), ('s31', 's.31 — Law enforcement'), ('s32', 's.32 — Court records'), ('s33', 's.33 — Audit functions'), ('s34', 's.34 — Parliamentary privilege'), ('s35', 's.35 — Formulation of government policy'), ('s36', 's.36 — Prejudice to effective conduct of public affairs'), ('s37', 's.37 — Communications with the Crown'), ('s38', 's.38 — Health and safety'), ('s39', 's.39 — Environmental information'), ('s40', 's.40 — Personal information'), ('s41', 's.41 — Information provided in confidence'), ('s42', 's.42 — Legal professional privilege'), ('s43', 's.43 — Commercial interests'), ('s44', 's.44 — Prohibitions on disclosure')], help_text='Optional. Link this block to a FOIA exemption so it is suggested on cases claiming that exemption. Leave blank for general explainers.', max_length=10),
        ),
    ]
