# Generated by Django 6.0.5 on 2026-08-15 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0018_alter_responsetemplate_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseCRUAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_sent_at', models.DateField(blank=True, null=True)),
                ('received_at', models.DateField(blank=True, null=True)),
                ('advice', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cru_advice', to='cases.case')),
            ],
            options={
                'verbose_name': 'CRU advice',
                'verbose_name_plural': 'CRU advice',
            },
        ),
    ]
