# Generated by Django 6.0.5 on 2026-08-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0019_casecruadvice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='outcome',
            field=models.CharField(blank=True, choices=[('disclosed_full', 'Information disclosed in full'), ('disclosed_part', 'Information disclosed in part'), ('not_held', 'Information not held'), ('refused', 'Request refused'), ('withdrawn', 'Request withdrawn'), ('clarification_not_received', 'Clarification not received')], max_length=30),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='purpose',
            field=models.CharField(blank=True, choices=[('acknowledgement', 'Acknowledgement'), ('case_response', 'Case Response'), ('consultation_notification', 'Consultation Notification'), ('consultation_message', 'Consultation Message'), ('case_assignment', 'Case Assignment'), ('clarification_request', 'Clarification Request'), ('verification_code', 'Verification Code')], max_length=40, null=True, unique=True),
        ),
    ]
