# Generated by Django 6.0.5 on 2026-08-22 22:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0020_alter_case_outcome_alter_emailtemplate_purpose'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['received_by', 'submitted_at'], name='cases_case_receive_ac12f6_idx'),
        ),
    ]
