# Generated by Django 6.0.5 on 2026-08-29 15:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0021_case_cases_case_receive_ac12f6_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='case',
            index=models.Index(fields=['status', 'statutory_deadline'], name='cases_case_status_c1195b_idx'),
        ),
    ]
