# Generated by Django 6.0.5 on 2026-08-29 21:10

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("cases", "0022_case_cases_case_status_c1195b_idx"),
        ("publications", "0003_remove_disclosurelogentry_is_published_and_more"),
    ]

    operations = [
        # Added by hand: `makemigrations` cannot infer an extension from a
        # model, and the tables below cannot be created without it. Needs
        # privileges a managed database user may not have — where it fails,
        # `CREATE EXTENSION vector;` has to be run by someone who does have
        # them, and `ai.W001` reports the state until it is.
        VectorExtension(),
        migrations.CreateModel(
            name="CaseEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_model", models.CharField(max_length=100)),
                ("content_hash", models.CharField(max_length=64)),
                ("embedded_at", models.DateTimeField(auto_now=True)),
                ("request_vector", pgvector.django.vector.VectorField(dimensions=768)),
                (
                    "case",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="cases.case",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["request_vector"],
                        m=16,
                        name="ai_case_request_vector_hnsw",
                        opclasses=["vector_cosine_ops"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="DisclosureLogEntryEmbedding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("embedding_model", models.CharField(max_length=100)),
                ("content_hash", models.CharField(max_length=64)),
                ("embedded_at", models.DateTimeField(auto_now=True)),
                ("request_vector", pgvector.django.vector.VectorField(dimensions=768)),
                (
                    "answer_vector",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                (
                    "entry",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="embedding",
                        to="publications.disclosurelogentry",
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["request_vector"],
                        m=16,
                        name="ai_entry_request_vector_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["answer_vector"],
                        m=16,
                        name="ai_entry_answer_vector_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                ],
            },
        ),
    ]
