from datetime import date

from django.conf import settings
from django.contrib.postgres.indexes import GinIndex
from django.contrib.postgres.search import SearchVector, SearchVectorField
from django.core.exceptions import ValidationError
from django.db import models
from django.utils import timezone

from apps.cases.utils import add_working_days, working_days_between


class BankHoliday(models.Model):
    class Country(models.TextChoices):
        ENGLAND = "england", "England"
        WALES = "wales", "Wales"
        SCOTLAND = "scotland", "Scotland"
        NORTHERN_IRELAND = "northern_ireland", "Northern Ireland"

    country = models.CharField(max_length=20, choices=Country.choices)
    name = models.CharField(max_length=100)
    date = models.DateField()

    class Meta:
        ordering = ["date", "country"]
        unique_together = [["date", "country"]]

    def __str__(self):
        return f"{self.date} — {self.name} ({self.get_country_display()})"


class RequesterCategory(models.Model):
    name = models.CharField(max_length=100, unique=True)
    order = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ["order", "name"]
        verbose_name_plural = "requester categories"

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(max_length=200, unique=True)
    internal_deadline_days = models.PositiveSmallIntegerField(default=10)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name


class Case(models.Model):
    class Status(models.TextChoices):
        NEW = "new", "New"
        ACKNOWLEDGED = "acknowledged", "Acknowledged"
        WITH_DEPARTMENT = "with_department", "With Department"
        DRAFTING = "drafting", "Drafting"
        REVIEW = "review", "In Review"
        WITH_APPLICANT = "with_applicant", "Awaiting Clarification"
        INTERNAL_REVIEW = "internal_review", "Internal Review"
        REFERRED = "referred", "Referred"
        EXEMPT = "exempt", "Refused / Exempt"
        CLOSED = "closed", "Closed"

    # Statuses where the case is finished — the statutory clock has stopped, so
    # a deadline in the past is history rather than a breach.
    TERMINAL_STATUSES = [Status.EXEMPT, Status.CLOSED]

    class Outcome(models.TextChoices):
        DISCLOSED_FULL = "disclosed_full", "Information disclosed in full"
        DISCLOSED_PART = "disclosed_part", "Information disclosed in part"
        NOT_HELD = "not_held", "Information not held"
        REFUSED = "refused", "Request refused"
        WITHDRAWN = "withdrawn", "Request withdrawn"
        CLARIFICATION_NOT_RECEIVED = (
            "clarification_not_received",
            "Clarification not received",
        )

    class ReceivedBy(models.TextChoices):
        PORTAL = "portal", "Public Portal"
        EMAIL = "email", "Email"
        POST = "post", "Post"
        OTHER = "other", "Other"

    # Reference
    ref = models.CharField(max_length=20, unique=True, editable=False)

    # Requester details
    requester_name = models.CharField(max_length=300)
    requester_email = models.EmailField()
    requester_type = models.CharField(max_length=100, blank=True)
    preferred_response_format = models.CharField(max_length=50, blank=True)

    # Request content
    request_text = models.TextField()
    summary = models.TextField(blank=True)

    # Status and workflow
    status = models.CharField(max_length=20, choices=Status.choices, default=Status.NEW)
    received_by = models.CharField(
        max_length=10, choices=ReceivedBy.choices, default=ReceivedBy.PORTAL
    )

    # Dates and deadlines
    submitted_at = models.DateTimeField(default=timezone.now)
    acknowledged_at = models.DateField(null=True, blank=True)
    statutory_deadline = models.DateField(null=True, blank=True)

    # Clock pause
    clock_paused = models.BooleanField(default=False)
    clock_paused_at = models.DateField(null=True, blank=True)
    clock_paused_days = models.PositiveSmallIntegerField(default=0)

    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="created_cases",
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="assigned_cases",
    )

    # How the request ended. Recorded when the response is sent rather than
    # derived from status or exemptions: "we do not hold this" and "here it all
    # is" are both a closed case with no exemption claimed, and the difference
    # is exactly what transparency statistics are counting.
    outcome = models.CharField(max_length=30, choices=Outcome.choices, blank=True)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Lexical half of the AI assistant's search. Generated by the database
    # rather than maintained in Python, which is the whole reason it can be
    # trusted: it is recomputed by Postgres on every write, so unlike the
    # embeddings alongside it there is no staleness to detect, no signal to
    # fire, no sweep to run and no `content_hash` to compare.
    #
    # `summary` outranks `request_text` because on an imported or well-kept
    # case the summary is the subject line, and a term matching there says more
    # than the same term buried in three pages of requester preamble.
    search_vector = models.GeneratedField(
        expression=SearchVector("summary", weight="A", config="english")
        + SearchVector("request_text", weight="B", config="english"),
        output_field=SearchVectorField(),
        db_persist=True,
    )

    class Meta:
        ordering = ["-submitted_at"]
        indexes = [
            # Serves the public submission throttle, which counts a single
            # address's portal cases inside a time window on every submission.
            # Without it that count is a table scan run once per attempt, so the
            # defence would get more expensive exactly as an attack got faster.
            models.Index(fields=["received_by", "submitted_at"]),
            # Serves the dashboard counters, which filter on status and then on
            # a `statutory_deadline` range for every tile on every page load.
            models.Index(fields=["status", "statutory_deadline"]),
            GinIndex(fields=["search_vector"], name="cases_case_search_gin"),
        ]

    def __str__(self):
        return f"{self.ref}: {self.request_text[:60]}"

    def save(self, *args, **kwargs):
        if not self.ref:
            self.ref = self._generate_ref()
        if not self.statutory_deadline and self.submitted_at:
            submitted_date = (
                self.submitted_at.date()
                if hasattr(self.submitted_at, "date")
                else self.submitted_at
            )
            self.statutory_deadline = add_working_days(
                submitted_date, settings.FOI_STATUTORY_DAYS
            )
        super().save(*args, **kwargs)

    @classmethod
    def _generate_ref(cls):
        prefix = getattr(settings, "FOI_REFERENCE_PREFIX", "FOI")
        year = timezone.now().year
        last = (
            cls.objects.filter(ref__startswith=f"{prefix}-{year}-")
            .order_by("-ref")
            .first()
        )
        if last:
            seq = int(last.ref.split("-")[-1]) + 1
        else:
            seq = 1
        return f"{prefix}-{year}-{seq:04d}"

    @property
    def is_overdue(self) -> bool:
        if not self.statutory_deadline:
            return False
        # A paused clock cannot be in breach. `resume_clock` only pushes
        # `statutory_deadline` out once the pause ends, so a case paused before
        # its deadline sits past that date for as long as the pause lasts —
        # without this check the service reports statutory breaches that did not
        # happen. `CaseViewSet.get_queryset` repeats this as a queryset
        # expression for the `is_overdue=true` filter; keep the two in step.
        return (
            date.today() > self.statutory_deadline
            and self.status not in self.TERMINAL_STATUSES
            and not self.clock_paused
        )

    def acknowledge(self, actor=None):
        today = date.today()
        self.acknowledged_at = today
        self.statutory_deadline = add_working_days(today, settings.FOI_STATUTORY_DAYS)
        self.status = self.Status.ACKNOWLEDGED
        self.save()
        self._log(action="acknowledged", actor=actor, detail={})

    def pause_clock(self, reason: str = "", actor=None):
        # Not pausable before acknowledgement. `acknowledge()` resets
        # `statutory_deadline` from the acknowledgement date outright, so a pause
        # taken before it would be silently forfeited — and a case acknowledged
        # while still flagged paused would be extended again on resume, by days
        # counted from a pause that began before the deadline it is applied to.
        # Blocking the earlier half of that pairing keeps `acknowledge()` simple.
        if self.clock_paused or not self.acknowledged_at:
            return
        self.clock_paused = True
        self.clock_paused_at = date.today()
        self.save()
        self._log(action="clock_paused", actor=actor, detail={"reason": reason})

    def resume_clock(self, actor=None):
        if not self.clock_paused or not self.clock_paused_at:
            return
        paused_days = working_days_between(self.clock_paused_at, date.today())
        self.clock_paused_days += paused_days
        self.clock_paused = False
        self.clock_paused_at = None
        if self.statutory_deadline:
            self.statutory_deadline = add_working_days(
                self.statutory_deadline, paused_days
            )
        self.save()
        self._log(
            action="clock_resumed", actor=actor, detail={"paused_days": paused_days}
        )

    def transition_to(self, new_status: str, actor=None):
        old_status = self.status
        self.status = new_status
        self.save()
        self._log(
            action="status_change",
            actor=actor,
            detail={"from": old_status, "to": new_status},
        )

    def _log(self, action: str, actor, detail: dict):
        CaseAuditEvent.objects.create(
            case=self,
            actor=actor,
            action=action,
            detail=detail,
        )


class Mailbox(models.Model):
    name = models.CharField(max_length=200, unique=True)
    email = models.EmailField(unique=True)

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "mailboxes"

    def __str__(self):
        return f"{self.name} <{self.email}>"


class EmailTemplate(models.Model):
    class Type(models.TextChoices):
        ASSIGNEE = "assignee", "Assignee"
        CONSULTATION = "consultation", "Consultation"
        REQUESTER = "requester", "Requester"

    class Purpose(models.TextChoices):
        ACKNOWLEDGEMENT = "acknowledgement", "Acknowledgement"
        CASE_RESPONSE = "case_response", "Case Response"
        CONSULTATION_NOTIFICATION = (
            "consultation_notification",
            "Consultation Notification",
        )
        CONSULTATION_MESSAGE = "consultation_message", "Consultation Message"
        CASE_ASSIGNMENT = "case_assignment", "Case Assignment"
        CLARIFICATION_REQUEST = "clarification_request", "Clarification Request"
        VERIFICATION_CODE = "verification_code", "Verification Code"

    PURPOSE_TYPE_MAP = {
        Purpose.ACKNOWLEDGEMENT: Type.REQUESTER,
        Purpose.CASE_RESPONSE: Type.REQUESTER,
        Purpose.CONSULTATION_NOTIFICATION: Type.CONSULTATION,
        Purpose.CONSULTATION_MESSAGE: Type.CONSULTATION,
        Purpose.CASE_ASSIGNMENT: Type.ASSIGNEE,
        Purpose.CLARIFICATION_REQUEST: Type.REQUESTER,
        Purpose.VERIFICATION_CODE: Type.REQUESTER,
    }

    #: Placeholders a template cannot do its job without.
    #:
    #: `render()` is a plain string replace, so a template that omits a variable
    #: does not fail — it sends the letter with the variable's content simply
    #: missing. For most purposes that is a cosmetic mistake someone notices. A
    #: verification email with no {{code}} in it is a working email that cannot
    #: possibly be acted on, sent to a member of the public who has no way to
    #: report the fault, so the mistake is caught at save time instead.
    PURPOSE_REQUIRED_VARIABLES = {
        Purpose.VERIFICATION_CODE: ["code"],
    }

    PURPOSE_META = {
        Purpose.ACKNOWLEDGEMENT: {
            "label": "Acknowledgement",
            "description": "Sent to the requester when their FOI request is acknowledged. Use {{request_text}} to quote their request back to them.",
            "variables": [
                "ref",
                "requester_name",
                "request_text",
                "submitted_at",
                "statutory_deadline",
                "organisation_name",
                "foi_contact_email",
            ],
        },
        Purpose.CASE_RESPONSE: {
            "label": "Case Response",
            "description": "Seeds a new response draft. Write the full letter — greeting, appeal rights and sign-off included. Use {{request_text}} to quote the requester's original request back to them, and {{response_body}} to mark where the officer starts writing (it is removed when the draft is created and the cursor placed there).",
            "variables": [
                "ref",
                "requester_name",
                "request_text",
                "response_body",
                "submitted_at",
                "statutory_deadline",
                "organisation_name",
                "foi_contact_email",
            ],
        },
        Purpose.CONSULTATION_NOTIFICATION: {
            "label": "Consultation Notification",
            "description": "Sent to an assignee when they are added to a consultation.",
            "variables": [
                "ref",
                "requester_name",
                "assignee_name",
                "scope",
                "due_date",
                "consultation_url",
                "organisation_name",
            ],
        },
        Purpose.CONSULTATION_MESSAGE: {
            "label": "Consultation Message",
            "description": "Sent to an assignee when a new message is posted on their consultation.",
            "variables": [
                "ref",
                "requester_name",
                "assignee_name",
                "message_body",
                "consultation_url",
                "organisation_name",
            ],
        },
        Purpose.CASE_ASSIGNMENT: {
            "label": "Case Assignment",
            "description": "Sent to a staff member when a case is assigned to them.",
            "variables": [
                "ref",
                "requester_name",
                "assignee_name",
                "case_url",
                "organisation_name",
            ],
        },
        Purpose.CLARIFICATION_REQUEST: {
            "label": "Clarification Request",
            "description": "Sent to the requester when further information is needed to process their FOI request. Use {{request_text}} to quote their original request and {{clarification_body}} to embed what the officer wrote in the clarification form. Sending this email pauses the statutory clock.",
            "variables": [
                "ref",
                "requester_name",
                "request_text",
                "clarification_body",
                "submitted_at",
                "organisation_name",
                "foi_contact_email",
            ],
        },
        Purpose.VERIFICATION_CODE: {
            "label": "Verification Code",
            "description": "Sent when someone asks to check the progress of their requests on the public portal. Must contain {{code}}. There are deliberately no case details available here — anyone can trigger this email by typing an address, so it must be safe to send to a stranger who is not the requester.",
            "variables": [
                "code",
                "expires_minutes",
                "organisation_name",
                "foi_contact_email",
            ],
        },
    }

    purpose = models.CharField(
        max_length=40, choices=Purpose.choices, unique=True, null=True, blank=True
    )
    name = models.CharField(max_length=200)
    type = models.CharField(max_length=20, choices=Type.choices, blank=True)
    description = models.TextField(blank=True)
    subject = models.CharField(max_length=500, blank=True)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["type", "name"]

    def __str__(self):
        return f"[{self.get_type_display()}] {self.name}"

    def missing_required_variables(self) -> list[str]:
        """Placeholders this template's purpose requires but the body omits."""
        if not self.purpose:
            return []
        required = self.PURPOSE_REQUIRED_VARIABLES.get(self.purpose, [])
        return [name for name in required if f"{{{{{name}}}}}" not in (self.body or "")]

    def clean(self):
        super().clean()
        missing = self.missing_required_variables()
        if missing:
            names = ", ".join(f"{{{{{name}}}}}" for name in missing)
            raise ValidationError(
                {"body": f"This template must include {names}."}
            )

    def save(self, *args, **kwargs):
        if self.purpose:
            self.type = self.PURPOSE_TYPE_MAP[self.purpose]
            # Enforced here and not only in clean(): save() is the one path
            # every caller shares, and the admin, a data migration and a shell
            # session all skip full_clean().
            self.clean()
        super().save(*args, **kwargs)

    def render(self, context: dict) -> str:
        result = self.body
        for key, value in context.items():
            result = result.replace(f"{{{{{key}}}}}", str(value))
        return result

    def render_subject(self, context: dict) -> str:
        result = self.subject
        for key, value in context.items():
            result = result.replace(f"{{{{{key}}}}}", str(value))
        return result


class CaseConsultation(models.Model):
    class Status(models.TextChoices):
        OPEN = "open", "Open"
        CLOSED = "closed", "Closed"
        WITHDRAWN = "withdrawn", "Withdrawn"

    case = models.ForeignKey(
        Case, on_delete=models.CASCADE, related_name="consultations"
    )
    assignee = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="consultations",
    )
    mailbox = models.ForeignKey(
        Mailbox,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="consultations",
    )
    scope = models.TextField()
    status = models.CharField(
        max_length=30, choices=Status.choices, default=Status.OPEN
    )
    due_date = models.DateField(null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="created_consultations",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        recipient = (
            self.assignee.get_full_name()
            if self.assignee
            else self.mailbox.name
            if self.mailbox
            else "Unassigned"
        )
        return f"{self.case.ref} → {recipient}"


class ConsultationMessage(models.Model):
    consultation = models.ForeignKey(
        CaseConsultation, on_delete=models.CASCADE, related_name="messages"
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __str__(self):
        return f"{self.consultation} — {self.created_at:%Y-%m-%d %H:%M}"


class CaseResponse(models.Model):
    class Status(models.TextChoices):
        DRAFT = "draft", "Draft"
        SENDING = "sending", "Sending"
        SENT = "sent", "Sent"
        FAILED = "failed", "Failed"

    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name="responses")
    body = models.TextField()
    rendered_body = models.TextField(blank=True)
    status = models.CharField(
        max_length=10, choices=Status.choices, default=Status.DRAFT
    )
    sent_at = models.DateTimeField(null=True, blank=True)
    created_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        null=True,
        blank=True,
        on_delete=models.SET_NULL,
        related_name="created_responses",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return f"{self.case.ref} response ({self.status})"


class CaseExemption(models.Model):
    class Code(models.TextChoices):
        S12_COST_LIMIT = "s12", "s.12 — Cost of compliance limit"
        S14_VEXATIOUS = "s14", "s.14 — Vexatious or repeated request"
        S21_PUBLICLY_AVAILABLE = "s21", "s.21 — Information accessible by other means"
        S22_FUTURE_PUBLICATION = "s22", "s.22 — Intended for future publication"
        S23_SECURITY_BODIES = "s23", "s.23 — Information supplied by security bodies"
        S24_NATIONAL_SECURITY = "s24", "s.24 — National security"
        S26_DEFENCE = "s26", "s.26 — Defence"
        S27_INTERNATIONAL_RELATIONS = "s27", "s.27 — International relations"
        S28_RELATIONS_WITHIN_UK = "s28", "s.28 — Relations within the UK"
        S29_ECONOMY = "s29", "s.29 — The economy"
        S30_INVESTIGATIONS = "s30", "s.30 — Investigations and proceedings"
        S31_LAW_ENFORCEMENT = "s31", "s.31 — Law enforcement"
        S32_COURT_RECORDS = "s32", "s.32 — Court records"
        S33_AUDIT = "s33", "s.33 — Audit functions"
        S34_PARLIAMENTARY_PRIVILEGE = "s34", "s.34 — Parliamentary privilege"
        S35_POLICY_FORMULATION = "s35", "s.35 — Formulation of government policy"
        S36_PREJUDICE = "s36", "s.36 — Prejudice to effective conduct of public affairs"
        S37_COMMUNICATIONS = "s37", "s.37 — Communications with the Crown"
        S38_HEALTH_AND_SAFETY = "s38", "s.38 — Health and safety"
        S39_ENVIRONMENTAL = "s39", "s.39 — Environmental information"
        S40_PERSONAL_INFO = "s40", "s.40 — Personal information"
        S41_CONFIDENTIAL = "s41", "s.41 — Information provided in confidence"
        S42_LEGAL_PRIVILEGE = "s42", "s.42 — Legal professional privilege"
        S43_COMMERCIAL = "s43", "s.43 — Commercial interests"
        S44_PROHIBITIONS = "s44", "s.44 — Prohibitions on disclosure"

    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name="exemptions")
    code = models.CharField(max_length=10, choices=Code.choices)
    notes = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["code"]
        unique_together = [["case", "code"]]

    def __str__(self):
        return f"{self.code} — {self.case.ref}"


class CaseNote(models.Model):
    case = models.ForeignKey(Case, on_delete=models.CASCADE, related_name="notes")
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, on_delete=models.SET_NULL
    )
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["created_at"]

    def __repr__(self):
        return f"<CaseNote: {self.body[:40]}>"


class CaseAuditEvent(models.Model):
    case = models.ForeignKey(
        Case, on_delete=models.CASCADE, related_name="audit_events"
    )
    actor = models.ForeignKey(
        settings.AUTH_USER_MODEL, null=True, blank=True, on_delete=models.SET_NULL
    )
    action = models.CharField(max_length=50)
    detail = models.JSONField(default=dict)
    timestamp = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["timestamp"]

    def __str__(self):
        return f"{self.timestamp:%Y-%m-%d %H:%M} — {self.action}"


class CaseClarification(models.Model):
    case = models.OneToOneField(
        Case, on_delete=models.CASCADE, related_name="clarification"
    )
    sent_at = models.DateField(null=True, blank=True)
    received_at = models.DateField(null=True, blank=True)
    notes = models.TextField(blank=True)

    def __str__(self):
        return f"Clarification for {self.case.ref}"


class CaseCRUAdvice(models.Model):
    """Advice from the NPCC Central Referral Unit on how to handle a request.

    The referral is made outside this system, so `request_sent_at` is entered by
    hand — a value in that field is what marks the case as referred to the CRU.
    """

    case = models.OneToOneField(
        Case, on_delete=models.CASCADE, related_name="cru_advice"
    )
    request_sent_at = models.DateField(null=True, blank=True)
    received_at = models.DateField(null=True, blank=True)
    advice = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = "CRU advice"
        verbose_name_plural = "CRU advice"

    def __str__(self):
        return f"CRU advice for {self.case.ref}"


class ResponseTemplate(models.Model):
    name = models.CharField(max_length=200)
    exemption_code = models.CharField(
        max_length=10,
        choices=CaseExemption.Code.choices,
        blank=True,
        help_text=(
            "Optional. Link this block to a FOIA exemption so it is suggested "
            "on cases claiming that exemption. Leave blank for general explainers."
        ),
    )
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["exemption_code", "name"]

    def __str__(self):
        return f"Response template: {self.name}"
