# Generated by Django 6.0.5 on 2026-05-09 20:58

import apps.publications.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSchemeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('who_we_are', 'Who we are and what we do'), ('finances', 'What we spend and how we spend it'), ('priorities', 'What our priorities are and how we are doing'), ('decisions', 'How we make decisions'), ('policies', 'Our policies and procedures'), ('lists_registers', 'Lists and registers'), ('services', 'The services we offer')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.publications.models._scheme_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
