# Generated by Django 6.0.5 on 2026-06-06 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0002_disclosurelogentry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disclosurelogentry",
            name="is_published",
        ),
        migrations.AddField(
            model_name="disclosurelogentry",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="disclosurelogentry",
            name="rejected_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rejected_disclosure_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="disclosurelogentry",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="disclosurelogentry",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="disclosurelogentry",
            name="date_received",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disclosurelogentry",
            name="date_responded",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disclosurelogentry",
            name="response_text",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="disclosurelogentry",
            name="summary",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="disclosurelogentry",
            name="title",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
