# Generated by Django 6.0.5 on 2026-08-30 18:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0023_case_search_vector_case_cases_case_search_gin'),
        ('documents', '0002_attachment'),
        ('publications', '0003_remove_disclosurelogentry_is_published_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disclosurelogentry',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('summary', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), '||', django.contrib.postgres.search.SearchVector('response_text', config='english', weight='C'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='disclosurelogentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pub_entry_search_gin'),
        ),
    ]
