# Generated by Django 6.0.5 on 2026-09-10 16:08

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.publications.models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_disclosurelogentry_search_vector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationSchemeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('link', 'Link to a web page'), ('document', 'Uploaded document')], max_length=20)),
                ('label', models.CharField(blank=True, max_length=300)),
                ('url', models.URLField(blank=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=apps.publications.models._scheme_upload_to)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='publicationschemeentry',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicationschemeentry',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_scheme_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicationschemeentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='publicationschemeitem',
            name='entry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='publications.publicationschemeentry'),
        ),
        # Moved ahead of the AddIndex below. The autodetector emitted the index
        # first, which fails with FieldDoesNotExist because a GIN index cannot
        # be built on a column that does not exist yet. `0004` got this right
        # only because it happened to touch nothing else.
        migrations.AddField(
            model_name='publicationschemeentry',
            name='search_vector',
            field=models.GeneratedField(db_persist=True, expression=django.contrib.postgres.search.CombinedSearchVector(django.contrib.postgres.search.SearchVector('title', config='english', weight='A'), '||', django.contrib.postgres.search.SearchVector('description', config='english', weight='B'), django.contrib.postgres.search.SearchConfig('english')), output_field=django.contrib.postgres.search.SearchVectorField()),
        ),
        migrations.AddIndex(
            model_name='publicationschemeentry',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='scheme_entry_search_gin'),
        ),
    ]
