# Generated by Django 6.0.5 on 2026-09-10 16:09

from django.db import migrations


def move_links_to_items(apps, schema_editor):
    """Turn each entry's single url/document pair into `PublicationSchemeItem`s.

    An entry could hold one of each, so this creates up to two items per row.
    The URL goes first, matching the order the public page rendered them in
    before this change ("View online" then "Download document").

    Labels are left blank on purpose. `display_label` falls back to the
    filename or the URL, which is accurate but plain, and inventing a label
    here would put words on the public page that nobody wrote.

    Files are not touched. The `document` column holds a path relative to
    `MEDIA_ROOT` and the new item points at the same path, so existing uploads
    keep working at their existing URLs — they simply do not gain the UUID
    directory that new uploads get.
    """
    Entry = apps.get_model("publications", "PublicationSchemeEntry")
    Item = apps.get_model("publications", "PublicationSchemeItem")

    items = []
    for entry in Entry.objects.all().iterator():
        if entry.url:
            items.append(
                Item(entry=entry, kind="link", url=entry.url, sort_order=0)
            )
        if entry.document:
            items.append(
                Item(
                    entry=entry,
                    kind="document",
                    document=entry.document,
                    sort_order=1,
                )
            )

    Item.objects.bulk_create(items)


def move_items_to_links(apps, schema_editor):
    """Best effort reverse: put the first item of each kind back on the entry.

    Lossy where an entry has more than one link or more than one document,
    which is the whole reason items exist. Reversing this migration on data
    created after it therefore drops the extras, and that is unavoidable —
    there is nowhere on the entry for them to go.
    """
    Entry = apps.get_model("publications", "PublicationSchemeEntry")
    Item = apps.get_model("publications", "PublicationSchemeItem")

    for entry in Entry.objects.all().iterator():
        items = Item.objects.filter(entry=entry).order_by("sort_order", "pk")
        link = items.filter(kind="link").first()
        document = items.filter(kind="document").first()
        entry.url = link.url if link else ""
        entry.document = document.document if document else None
        entry.save(update_fields=["url", "document"])

    Item.objects.all().delete()


def publish_existing_entries(apps, schema_editor):
    """Everything that predates the draft state is already on the public site.

    `status` defaults to draft, so without this the migration would silently
    empty the publication scheme page — a statutory publication disappearing
    with no error anywhere to say why.

    `published_by` stays null. Nobody made this decision; it was the behaviour
    before there was a decision to make, and attributing it to whoever happens
    to run the migration would be false. `published_at` is left null for the
    same reason — `created_at` is the honest date and is already on the row.
    """
    Entry = apps.get_model("publications", "PublicationSchemeEntry")
    Entry.objects.update(status="published")


def unpublish_all_entries(apps, schema_editor):
    Entry = apps.get_model("publications", "PublicationSchemeEntry")
    Entry.objects.update(status="draft")


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_publicationschemeitem_and_more'),
    ]

    operations = [
        migrations.RunPython(publish_existing_entries, unpublish_all_entries),
        migrations.RunPython(move_links_to_items, move_items_to_links),
    ]
