# Generated by Django 6.0.5 on 2026-09-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_move_scheme_links_to_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicationschemeentry',
            name='document',
        ),
        migrations.RemoveField(
            model_name='publicationschemeentry',
            name='url',
        ),
    ]
